# Generated by Django 2.1 on 2020-03-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwal',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
