# Generated by Django 2.1 on 2020-03-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0002_auto_20200315_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
