# Generated by Django 2.1 on 2020-03-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal', '0003_auto_20200315_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jadwal',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='jadwal',
            old_name='start_date',
            new_name='start',
        ),
    ]
