# Generated by Django 2.1 on 2020-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('jabatan', models.CharField(choices=[{'status', 'anggota'}, {'pengurus', 'status'}], max_length=40)),
            ],
        ),
    ]
