# Generated by Django 2.1 on 2020-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='status',
            field=models.CharField(choices=[{'anggota', 'status'}, {'pengurus', 'status'}], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(max_length=100),
        ),
    ]
