# Generated by Django 2.1 on 2020-03-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_auto_20200315_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='status',
            field=models.CharField(choices=[('status', 'anggota'), ('status', 'pengurus')], max_length=40),
        ),
    ]
