# Generated by Django 2.1 on 2020-03-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0005_auto_20200315_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anggota',
            name='status',
            field=models.CharField(choices=[('anggota', 'anggota'), ('pengurus', 'pengurus')], max_length=40),
        ),
    ]
