# Generated by Django 2.1 on 2020-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0006_auto_20200329_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.jpeg', upload_to='profile_pic'),
        ),
    ]
