# Generated by Django 2.1 on 2020-03-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_berita_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='Kategory',
            field=models.ManyToManyField(related_name='kategori', to='berita.Kategory'),
        ),
    ]
