# Generated by Django 2.1 on 2020-03-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_auto_20200314_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='Kategory',
            new_name='kategori',
        ),
    ]
