# Generated by Django 2.1 on 2020-03-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_auto_20200314_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='slug',
            field=models.SlugField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
