# Generated by Django 2.1 on 2020-03-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_berita_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='slug',
            field=models.SlugField(editable=False, max_length=225),
        ),
    ]
